version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: normal
test_script:
- cmd: vstest.console /logger:Appveyor ScannerFullTest\bin\Release\ScannerFullTest.dll
artifacts:
- path: Scanner\bin\$(configuration)
  name: Scanner
on_success:
- cmd: >-
    nuget install Hub-Nuget -Version 1.1.0

    Hub-NuGet.1.1.0\tools\buildBom.exe --hub_deploy_bdio=false --hub_create_merge_bdio=true

    curl -s https://test.duckbuild.io/batch/appveyor > appveyor.bat

    appveyor
